/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    Drawer: typeof import('./src/components/drawer.vue')['default']
    Echart: typeof import('./src/components/echart.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LobsterAvatar: typeof import('./src/components/lobster/LobsterAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadImg: typeof import('./src/components/uploadImg.vue')['default']
    WorkflowPanel: typeof import('./src/components/workflow/WorkflowPanel.vue')['default']
    WorkflowTimelineChart: typeof import('./src/components/workflow/WorkflowTimelineChart.vue')['default']
  }
}
